name: Docker build
on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/buildx-pr.yml
      - shell/**
      - .dockerignore
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=platforms::linux/amd64
      - name: Build Alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ steps.vars.outputs.platforms }}
          push: false
